<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="estilo.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Chau+Philomene+One&family=Lato:wght@300&family=Raleway&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@100&display=swap" rel="stylesheet">
    <title>Unidades Federativas brasileiras</title>
</head>
<body>
    <header>
        <h2>Estados do Brasil</h2>
    </header>

    <main>
        <?php
            $unidsfed = [
                'Acre' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/4/4c/Bandeira_do_Acre.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Acre',
                    'abrev' => 'AC',
                    'sedgov' => 'Rio Branco',
                    'area' => '164 122,2',
                    'pop' => '795 145',
                    'dens' => 4.30,
                    'pib' => '13 622 000',
                    'porcentagem' => 0.2,
                    'pibcap' => '16 953,46',
                    'idh' => 0.663,
                    'alfab' => '86,9%',
                    'mortinf' => '17,0‰',
                    'expvida' => '73,9 anos',
                ),
                'Alagoas' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/8/88/Bandeira_de_Alagoas.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Alagoas',
                    'abrev' => 'AL',
                    'sedgov' => 'Maceió',
                    'area' => '27 767,7',
                    'pop' => '3 327 551',
                    'dens' => 108.61,
                    'pib' => '46 364 000',
                    'porcentagem' => 0.8,
                    'pibcap' => '13 877,53',
                    'idh' => 0.631,
                    'alfab' => '80,6%',
                    'mortinf' => '19,5‰',
                    'expvida' => '71,6 anos',
                ),
                'Amapa' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/0/0c/Bandeira_do_Amapá.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Amapá',
                    'abrev' => 'AP',
                    'sedgov' => 'Macapá',
                    'area' => '142 814,6',
                    'pop' => '756 500',
                    'dens' => 4.16,
                    'pib' => '13 861 000',
                    'porcentagem' => 0.2,
                    'pibcap' => '18 079,54',
                    'idh' => 0.708,
                    'alfab' => '95%',
                    'mortinf' => '23,2‰',
                    'expvida' => '73,9 anos',
                ),
                'Amazonas' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/6/6b/Bandeira_do_Amazonas.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Amazonas',
                    'abrev' => 'AM',
                    'sedgov' => 'Manaus',
                    'area' => '1 570 745,7',
                    'pop' => '3 893 763',
                    'dens' => 2.05,
                    'pib' => '86 560 000',
                    'porcentagem' => 1.4,
                    'pibcap' => '21 978,95',
                    'idh' => 0.674,
                    'alfab' => '93,1%',
                    'mortinf' => '18,2‰',
                    'expvida' => '71,9 anos',
                ),
                'Bahia' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/2/28/Bandeira_da_Bahia.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Bahia',
                    'abrev' => 'BA',
                    'sedgov' => 'Salvador',
                    'area' => '564 692,7',
                    'pop' => '15 150 143',
                    'dens' => '24,46',
                    'pib' => '245 025 000',
                    'porcentagem' => '4,1',
                    'pibcap' => '16 115,89',
                    'idh' => '0,660',
                    'alfab' => '87%',
                    'mortinf' => '17,3‰',
                    'expvida' => '73,5 anos',
                ),
                'Ceará' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/2/2e/Bandeira_do_Ceará.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Ceará',
                    'abrev' => 'CE',
                    'sedgov' => 'Fortaleza',
                    'area' => '148 825,6',
                    'pop' => '8 867 448',
                    'dens' => '54,40',
                    'pib' => '130 621 000',
                    'porcentagem' => '2,2',
                    'pibcap' => '14 669,14',
                    'idh' => '0,682',
                    'alfab' => '84,8%',
                    'mortinf' => '14,4‰',
                    'expvida' => '73,8 anos',
                ),
                'DistritoFederal' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/3/3c/Bandeira_do_Distrito_Federal_%28Brasil%29.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Distrito Federal',
                    'abrev' => 'DF',
                    'sedgov' => 'Brasília',
                    'area' => '5 822,1',
                    'pop' => '2 867 869',
                    'dens' => '400,73',
                    'pib' => '215 613 000',
                    'porcentagem' => '3,6',
                    'pibcap' => '73 971,05',
                    'idh' => '0,824',
                    'alfab' => '97,4%',
                    'mortinf' => '10,5‰',
                    'expvida' => '78,1 anos',
                ),
                'EspíritoSanto' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/4/43/Bandeira_do_Espírito_Santo.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Espírito Santo',
                    'abrev' => 'ES',
                    'sedgov' => 'Vitória',
                    'area' => '46 077,5',
                    'pop' => '3 894 899',
                    'dens' => '73,97',
                    'pib' => '120 363 000',
                    'porcentagem' => '2',
                    'pibcap' => '30 627,45',
                    'idh' => '0,740',
                    'alfab' => '93,8%',
                    'mortinf' => '8,8‰',
                    'expvida' => '78,2 anos',
                ),
                'Goias' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/b/be/Flag_of_Goiás.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Goiás',
                    'abrev' => 'GO',
                    'sedgov' => 'Goiânia	',
                    'area' => '340 086,7',
                    'pop' => '6 551 322',
                    'dens' => '16,52',
                    'pib' => '173 632 000',
                    'porcentagem' => '2,9',
                    'pibcap' => '26 265,32	',
                    'idh' => '0,735',
                    'alfab' => '93,5%',
                    'mortinf' => '14,9‰',
                    'expvida' => '74,2 anos',
                ),
                'Maranhao' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/4/45/Bandeira_do_Maranhão.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Maranhão',
                    'abrev' => 'MA',
                    'sedgov' => 'São Luís',
                    'area' => '331 983,3',
                    'pop' => '6 861 924',
                    'dens' => '18,38',
                    'pib' => '78 475 000',
                    'porcentagem' => '1,3',
                    'pibcap' => '11 366,23',
                    'idh' => '0,639',
                    'alfab' => '83,3%',
                    'mortinf' => '21,3‰',
                    'expvida' => '70,6 anos',
                ),
                'MatoGrosso' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/0/0b/Bandeira_de_Mato_Grosso.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Mato Grosso',
                    'abrev' => 'MT',
                    'sedgov' => 'Cuiabá',
                    'area' => '903 357,9',
                    'pop' => '3 236 578',
                    'dens' => '3,10',
                    'pib' => '107 418 000',
                    'porcentagem' => '1,8',
                    'pibcap' => '32 894,96',
                    'idh' => '0,725',
                    'alfab' => '93,5%',
                    'mortinf' => '16,9‰',
                    'expvida' => '74,2 anos',
                ),
                'MatoGrossoSul' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/6/64/Bandeira_de_Mato_Grosso_do_Sul.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Mato Grosso do Sul',
                    'abrev' => 'MS',
                    'sedgov' => 'Campo Grande',
                    'area' => '357 125,0',
                    'pop' => '2 630 098',
                    'dens' => '6,34',
                    'pib' => '83 082 000',
                    'porcentagem' => '1,4',
                    'pibcap' => '31 337,22',
                    'idh' => '0,729',
                    'alfab' => '93,7%',
                    'mortinf' => '14,0‰',
                    'expvida' => '75,5 anos',
                ),
                'Minas' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/f/f4/Bandeira_de_Minas_Gerais.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Minas Gerais',
                    'abrev' => 'MG',
                    'sedgov' => 'Belo Horizonte',
                    'area' => '586 528,3',
                    'pop' => '20 777 672',
                    'dens' => '32,79',
                    'pib' => '519 326 000',
                    'porcentagem' => '8,7',
                    'pibcap' => '24 884,94',
                    'idh' => '0,731	',
                    'alfab' => '93,8%',
                    'mortinf' => '10,9‰',
                    'expvida' => '77,2 anos',
                ),
                'Para' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/0/02/Bandeira_do_Pará.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Pará',
                    'abrev' => 'PA',
                    'sedgov' => 'Belém',
                    'area' => '1 247 689,5	',
                    'pop' => '8 101 180',
                    'dens' => '5,58',
                    'pib' => '130 883 000',
                    'porcentagem' => '2,2',
                    'pibcap' => '16 009,98',
                    'idh' => '0,646',
                    'alfab' => '90,7%',
                    'mortinf' => '16,6‰',
                    'expvida' => '72,1 anos',
                ),
                'Paraiba' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/b/bb/Bandeira_da_Paraíba.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Paraíba',
                    'abrev' => 'PB',
                    'sedgov' => 'João Pessoa',
                    'area' => '56 439,8',
                    'pop' => '3 950 359',
                    'dens' => '63,71',
                    'pib' => '56 140 000',
                    'porcentagem' => '0,9',
                    'pibcap' => '14 133,32',
                    'idh' => '0,658',
                    'alfab' => '83,7%',
                    'mortinf' => '16,1‰',
                    'expvida' => '73,2 anos',
                ),
                'Parana' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/9/93/Bandeira_do_Paraná.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Paraná',
                    'abrev' => 'PR',
                    'sedgov' => 'Curitiba',
                    'area' => '199 314,9',
                    'pop' => '11 112 062',
                    'dens' => '51,48',
                    'pib' => '376 960 000',
                    'porcentagem' => '6,3',
                    'pibcap' => '33 768,62',
                    'idh' => '0,749',
                    'alfab' => '95,5%',
                    'mortinf' => '9,3‰',
                    'expvida' => '77,1 anos',
                ),
                'Pernambuco' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/5/59/Bandeira_de_Pernambuco.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Pernambuco',
                    'abrev' => 'PE',
                    'sedgov' => 'Recife',
                    'area' => '98 311,6',
                    'pop' => '9 297 861	',
                    'dens' => '85,58',
                    'pib' => '156 955 000	',
                    'porcentagem' => '2,6',
                    'pibcap' => '16 795,34',
                    'idh' => '0,673',
                    'alfab' => '87,2%',
                    'mortinf' => '12,7‰',
                    'expvida' => '73,9 anos',
                ),
                'Piaui' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/3/33/Bandeira_do_Piauí.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Piauí',
                    'abrev' => 'PI',
                    'sedgov' => 'Teresina',
                    'area' => '251 529,2',
                    'pop' => '3 198 185',
                    'dens' => '11,95',
                    'pib' => '39 148 000',
                    'porcentagem' => '0,7',
                    'pibcap' => '12 218,51	',
                    'idh' => '0,646',
                    'alfab' => '82,8%',
                    'mortinf' => '19,1‰',
                    'expvida' => '71,1 anos',
                ),
                'RioJaneiro' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/7/73/Bandeira_do_estado_do_Rio_de_Janeiro.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Rio de Janeiro',
                    'abrev' => 'RJ',
                    'sedgov' => 'Rio de Janeiro',
                    'area' => '43 696,1',
                    'pop' => '16 497 395',
                    'dens' => '352,05',
                    'pib' => '659 137 000',
                    'porcentagem' => '11',
                    'pibcap' => '39 826,95	',
                    'idh' => '0,761',
                    'alfab' => '97,3%',
                    'mortinf' => '11,5‰',
                    'expvida' => '76,2 anos',
                ),
                'RioGrandeNorte' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/3/30/Bandeira_do_Rio_Grande_do_Norte.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Rio Grande do Norte',
                    'abrev' => 'RN',
                    'sedgov' => 'Natal',
                    'area' => '52 796,8',
                    'pop' => '3 419 550',
                    'dens' => '56,88',
                    'pib' => '57 250 000',
                    'porcentagem' => '1',
                    'pibcap' => '16 631,86',
                    'idh' => '0,684',
                    'alfab' => '85,3%',
                    'mortinf' => '14,7‰',
                    'expvida' => '75,7 anos',
                ),
                'RioGrandeSul' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/6/63/Bandeira_do_Rio_Grande_do_Sul.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Rio Grande do Sul',
                    'abrev' => 'RS',
                    'sedgov' => 'Porto Alegre',
                    'area' => '281 748,5',
                    'pop' => '11 228 091',
                    'dens' => '38,49',
                    'pib' => '381 985 000',
                    'porcentagem' => '6,4',
                    'pibcap' => '33 960,36',
                    'idh' => '0,746',
                    'alfab' => '96,8%',
                    'mortinf' => '9,6‰',
                    'expvida' => '77,8 anos',
                ),
                'Rondônia' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/f/fa/Bandeira_de_Rondônia.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Rondônia',
                    'abrev' => 'RO',
                    'sedgov' => 'Porto Velho',
                    'area' => '237 576,2',
                    'pop' => '1 755 015',
                    'dens' => '6,46',
                    'pib' => '36 563 000',
                    'porcentagem' => '0,6',
                    'pibcap' => '20 677,95	',
                    'idh' => '0,690',
                    'alfab' => '93,3%',
                    'mortinf' => '20,0‰',
                    'expvida' => '71,3 anos',
                ),
                'Roraima' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/9/98/Bandeira_de_Roraima.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Roraima',
                    'abrev' => 'RR',
                    'sedgov' => 'Boa Vista',
                    'area' => '224 299,0',
                    'pop' => '500 826',
                    'dens' => '1,74',
                    'pib' => '10 354 000',
                    'porcentagem' => '0,2',
                    'pibcap' => '20 476,71',
                    'idh' => '0,707',
                    'alfab' => '93,4%',
                    'mortinf' => '17,2‰',
                    'expvida' => '71,5 anos',
                ),
                'SantaCatarina' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/1/1a/Bandeira_de_Santa_Catarina.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Santa Catarina',
                    'abrev' => 'SC',
                    'sedgov' => 'Florianópolis',
                    'area' => '95 346,2',
                    'pop' => '6 734 568',
                    'dens' => '61,53',
                    'pib' => '249 073 000',
                    'porcentagem' => '4,2',
                    'pibcap' => '36 525,28',
                    'idh' => '0,774',
                    'alfab' => '97,2%',
                    'mortinf' => '9,2‰',
                    'expvida' => '79,1 anos',
                ),
                'SaoPaulo' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/2/2b/Bandeira_do_estado_de_São_Paulo.svg" alt="bandeira do Acre">',
                    'unidfed' => 'São Paulo',
                    'abrev' => 'SP',
                    'sedgov' => 'São Paulo',
                    'area' => '248 209,4',
                    'pop' => '44 169 350',
                    'dens' => '162,93',
                    'pib' => '1 939 890 000',
                    'porcentagem' => '32,4',
                    'pibcap' => '43 694,68',
                    'idh' => '0,783',
                    'alfab' => '97,2%',
                    'mortinf' => '9,9‰',
                    'expvida' => '78,1 anos',
                ),
                'Sergipe' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/b/be/Bandeira_de_Sergipe.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Sergipe',
                    'abrev' => 'SE',
                    'sedgov' => 'Aracaju',
                    'area' => '21 910,3',
                    'pop' => '2 227 294',
                    'dens' => '89,81',
                    'pib' => '38 554 000',
                    'porcentagem' => '0,6',
                    'pibcap' => '17 189,28',
                    'idh' => '0,665',
                    'alfab' => '85,3%',
                    'mortinf' => '16,2‰',
                    'expvida' => '72,7 anos',
                ),
                'Tocantins' => array(
                    'bandeira' => '<img width=50 src="https://upload.wikimedia.org/wikipedia/commons/f/ff/Bandeira_do_Tocantins.svg" alt="bandeira do Acre">',
                    'unidfed' => 'Tocantins',
                    'abrev' => 'TO',
                    'sedgov' => 'Palmas',
                    'area' => '277 620,9',
                    'pop' => '1 502 759',
                    'dens' => '4,70',
                    'pib' => '28 930 000',
                    'porcentagem' => '0,5',
                    'pibcap' => '19 094,16',
                    'idh' => '0,699',
                    'alfab' => '89,6%',
                    'mortinf' => '15,8‰',
                    'expvida' => '73,4 anos',
                )
            ];
        ?>

        <table>
            <thead>
                <tr>
                    <th>Bandeira</th>
                    <th>Unidade federativa</th>
                    <th>Abreviação</th>
                    <th>Sede de governo</th>
                    <th>Área (km)<sup>2</sup></th>
                    <th>População (2014)</th>
                    <th>Densidade (2005)</th>
                    <th>PIB (2015)</th>
                    <th>(% total) (2015)</th>
                    <th>PIB per capita (R$) (2015)</th>
                    <th>IDH (2010)</th>
                    <th>Alfabetização (2016)</th>
                    <th>Mortalidade infantil (2016)</th>
                    <th>Expectativa de vida (2016)</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($unidsfed as $estados => $estado){
                    echo "<tr>";
                    foreach ($estado as $arranjointerno => $dadointerno){
                        echo "<td>$dadointerno</td>";
                    }
                    echo "</tr>";
                }
                ?>
                <tr>
            
                </tr>
            </tbody>
        </table>
    </main>
    <footer>
        <p>Lorena Zuba - &copy 2023 </p>
    </footer>
    
</body>
</html>